can run under Dash

diff --git a/script/lib.sh.in b/script/lib.sh.in
--- a/script/lib.sh.in
+++ b/script/lib.sh.in
@@ -1,6 +1,7 @@
 # lib.sh
 
 wait_mbd() {
+    local dev
     for sun in shining the weather is sweet; do
         dev=$(blkid -l -o device -t LABEL='@mbd_label@')
         [ ${?} -eq 0 ] && [ -n "${dev}" ] && return 0
@@ -10,15 +11,15 @@ wait_mbd() {
 }
 
 find_mount_mbd() {
-    local mount_point="${1}"
+    local err; local dev; local mount_point="${1}"
     wait_mbd
-    local dev=$(blkid -l -o device -t LABEL='@mbd_label@')
+    dev=$(blkid -l -o device -t LABEL='@mbd_label@')
     [ ${?} -eq 0 ] && [ -n "${dev}" ] || panic "No device with label \"@mbd_label@\""
-    local err=$(modprobe vfat 2>&1)
+    err=$(modprobe vfat 2>&1) || panic "Cannot load vfat module: ${err}" 
     mkdir -p "${mount_point}"
-    local err=$(mount -t vfat "${dev}" "${mount_point}") || panic "Cannot mount ${dev} : \"${err}\""
+    err=$(mount -t vfat "${dev}" "${mount_point}") || panic "Cannot mount ${dev} : \"${err}\""
     [ -f "${mount_point}/@isolinux_dir@/@magic@" ] || panic "Cannot find \"@mbd_verbose@\" installation"
-    mbd_device=${dev}
+    mbd_device="${dev}"
 }
 
 tune_command_line() {
@@ -47,7 +48,6 @@ kexec_load() {
     if [ -n "${initrd}" ];then
 	initrd="--initrd=${initrd}"
     fi
-    kexec --load "${kernel}" --command-line="${append}" "${initrd}"
-    [ ${?} -eq 0 ] || return 1
+    kexec --load "${kernel}" --command-line="${append}" "${initrd}" || return 1
     sync
 }
diff --git a/script/mbd_menu.in b/script/mbd_menu.in
--- a/script/mbd_menu.in
+++ b/script/mbd_menu.in
@@ -26,25 +26,25 @@ panic() {
 
 kexec_to() {
     local wdir="${1}"; local image="${2}"
-    local kernel=''; local append=''; local initrd=''
     cat "${wdir}/isolinux_entry" | prepare_kexec_parameters "${wdir}/mp" > "${wdir}/kexec_parameters"
     [ ${?} -eq 0 ] || { echo 'error preparing kexc parameters.'; return 1; }
-    cat "${wdir}/kexec_parameters" | {
-        read kernel
-        read initrd
-        read append
-         err=$(kexec_load "${wdir}" "${kernel}" "${append}" "${initrd}" "${mbd_initrd}" "${image}" 2>&1)
-    }
+    local err; err=$(cat "${wdir}/kexec_parameters" | {
+            local kernel; read kernel
+            local initrd; read initrd
+            local append; read append
+            kexec_load "${wdir}" "${kernel}" "${append}" "${initrd}" "${mbd_initrd}" "${image}"
+        } 2>&1)
     if [ ${?} -eq 0 ]; then
         sync
         umount -a
         mount -o remount,ro /
-        kexec -e
+        err=$(kexec -e)
     fi
     echo "kexec fail. ${err}"
 }
 
 parse_args() {
+    local opt
     while getopts ':t:i:y' opt; do
         case ${opt} in
             t)
@@ -66,9 +66,10 @@ parse_args() {
 }
 
 directory_menu() {
-    dialog_menu 'What would you like to boot?'
+    local node; local name
+    dialog_menu 'What would you like to boot?' || return 1
     for node in "${1}"/*; do
-        local name="${node##*/}"
+        name="${node##*/}"
         if [ -d "${node}" ]; then
             echo "'${name}' '/'"
         elif [ "${node}" != "${node%.[Ii][Ss][oO]}" ]; then
@@ -104,7 +105,8 @@ iso_menu() {
 
 iso_dialog() {
     local image="${1}/${2}"
-    local wdir="${tmp_dir}"$(readlink -f "${image}")
+    local err; local cmd; local wdir
+    wdir="${tmp_dir}"$(readlink -f "${image}")
     [ -x './@mbd_process_iso@' ] && cmd='./@mbd_process_iso@' || cmd='@mbd_process_iso@'
     err=$("${cmd}" "${wdir}" "${image}" 2>&1)
     if [ ! ${?} -eq 0 ] || [ ! -r "${wdir}/isolinux.cfg" ]; then
@@ -131,9 +133,9 @@ entry_menu() {
 }
 
 entry_dialog() {
-    local wdir="${1}"; local image="${2}"; local entry_name="${3}"
-    local entry=$(cat "${wdir}/isolinux.cfg" | isolinux_extract_entry "${choose}")
-    [ ${?} -eq 0 ] || { echo "error extracting label. ${err}"; return 1; }
+    local err; local wdir="${1}"; local image="${2}"; local entry_name="${3}"
+    local entry; entry=$(cat "${wdir}/isolinux.cfg" | isolinux_extract_entry "${choose}")
+    [ ${?} -eq 0 ] || { echo "error extracting label. ${entry}"; return 1; }
     local i
     for i in 'label' 'kernel' 'append'; do
         i=$(echo "${entry}" | sed -ne "s_^${i}\s\+\(.*\)_\1_p")
