boot from running system

diff --git a/script/lib.sh.in b/script/lib.sh.in
--- a/script/lib.sh.in
+++ b/script/lib.sh.in
@@ -1,38 +1,44 @@
 
 wait_mbd() {
-    for sing in sun is shining the weather is sweet; do
+    for sun in shining the weather is sweet; do
         dev=$(blkid -l -o device -t LABEL='@mbd_label@')
-        [ 0 = ${?} ] && [ -n "${dev}" ] && return 0
+        [ ${?} -eq 0 ] && [ -n "${dev}" ] && return 0
         sleep 2
     done
     return 1
 }
 
 find_mount_mbd() {
+    local mount_point="${1}"
     wait_mbd
-    dev=$(blkid -l -o device -t LABEL='@mbd_label@')
-    [ 0 = ${?} ] && [ -n "${dev}" ] || panic "No device with label \"@mbd_label@\""
-    err=$(modprobe vfat 2>&1)
-    mkdir -p '@mbd_dir@/mnt'
-    err=$(mount -t vfat "${dev}" '@mbd_dir@/mnt') || panic "Cannot mount ${dev} : \"${err}\""
-    [ -f '@mbd_dir@/mnt/@isolinux_dir@/@magic@' ] || panic "Cannot find \"@mbd_verbose@\" installation"
+    local dev=$(blkid -l -o device -t LABEL='@mbd_label@')
+    [ ${?} -eq 0 ] && [ -n "${dev}" ] || panic "No device with label \"@mbd_label@\""
+    local err=$(modprobe vfat 2>&1)
+    mkdir -p "${mount_point}"
+    local err=$(mount -t vfat "${dev}" "${mount_point}") || panic "Cannot mount ${dev} : \"${err}\""
+    [ -f "${mount_point}/@isolinux_dir@/@magic@" ] || panic "Cannot find \"@mbd_verbose@\" installation"
     mbd_device=${dev}
 }
 
 tune_command_line() {
-    image="@mbd_dir@/mnt/@images_dir@/${1}"
+    local image="@mbd_dir@/mnt/@images_dir@/${1}"
     sed -e "
     s|root=\S*||
+    s|--||
     s|\(boot=live\)|\1 fromiso=@mbd_dir@/device/@images_dir@/${1}|
     s|\(boot=casper\)|\1 iso-scan/filename=/@images_dir@/${1}|
     s|^|rdinit=@mbd_dir@/init boot_image=${image} root=live:/dev/@loop_dev@ cdroot=/dev/@loop_dev@ bootfrom=/dev/@loop_dev@ |
     "
 }
 
-kexec_load() {    
-    wdir="${1}"; kernel="${2}"; append="${3}"; initrd="${4}"; mbd_initrd="${5}"; image="${6}"
-    [ -n "${kernel}" ] && [ -n "${append}" ] || panic "Bad boot arguments"
+kexec_load() {
+    local wdir="${1}"; local kernel="${2}"; local append="${3}"
+    local initrd="${4}"; local mbd_initrd="${5}"; local image="${6}"
+    [ -n "${kernel}" ] && [ -n "${append}" ] || { echo "Bad boot arguments"; return 1; }
+    [ -f "${kernel}" ] || { echo "Cannot open \"${kernel}\""; return 1; }
     if [ -n "${initrd}" ] &&  [ -n "${mbd_initrd}" ]; then
+        [ -f "${initrd}" ] || { echo "Cannot open \"${initrd}\""; return 1; }
+        [ -f "${mbd_initrd}" ] || { echo "Cannot open \"${mbd_initrd}\""; return 1; }
 	cat "${initrd}" "${mbd_initrd}" >> "${wdir}/mbd_combined_initrd"
 	initrd="${wdir}/mbd_combined_initrd"
         append="$(echo ${append} | tune_command_line ${image})"
diff --git a/script/mbd_menu.in b/script/mbd_menu.in
--- a/script/mbd_menu.in
+++ b/script/mbd_menu.in
@@ -1,92 +1,97 @@
 #!/bin/sh
 
+@include_script_lib@
+@include_dialog_lib@
+
+usage() {
+    cat << EOF
+usage: $0 [-y] [-t dir] [-i initrd] [dir]
+-y        :  do not ask for confirmation
+-t dir    :  directory to store temporary files
+-i initrd :  initrd to inject
+dir       :  directory for processing
+EOF
+}
+
 exit_to_shell() {
-    echo "Type \"@mbd_command@\" to return to the \"@mbd_verbose@\" menu."
     exit 0
 }
 
 panic() {
-    echo "${1}"
+    show error_msg "${msg}"
+    echo "${1}" >&2
     exit_to_shell
-}
-
-@include_script_lib@
-
-netbootcd() {
-    if [ -x /tmp/nbscript.sh ];then
-	/tmp/nbscript.sh
-    else
-	/usr/bin/nbscript.sh
-    fi
-}
-
-show() {    
-    choose=''
-    what=${1}; shift
-    arg=$(echo "$*" | sed -e "s_'__g")
-    exec 3>&1
-    choose=$(${what} "${arg}" | xargs dialog 2>&1 1>&3)
-    err=$?
-    exec 3>&-
-    return ${err}
-}
-
-error_msg() {
-    echo "--backtitle \"@mbd_verbose@\" --msgbox '${1}' 20 70"
-}
-
-dialog_menu() {
-    echo "--backtitle \"@mbd_verbose@\" --menu '${1}' 20 70 13"
-}
-
-main_menu() {
-    dialog_menu "What would you like to do?"
-    echo "'Live' 'Boot image'"
-    echo "'NetbootCD' 'Run NetbootCD script'"
 }
 
 images_menu() {
     dialog_menu "What would you like to boot?"
-    for image in '@mbd_dir@/mnt/@images_dir@/'*.iso; do
+    for image in "${images_dir}/"*.iso; do
         image="${image##*/}"; image="${image%.iso}"
         echo "'${image}' ''"
     done
 }
 
+kexec_to() {
+    choose="${1}"
+    . "${tmp_dir}/boot_default"
+    err=$(kexec_load "${tmp_dir}" "${kernel}" "${append}" "${initrd}" "${mbd_initrd}" "${choose}.iso" 2>&1)
+    if [ ${?} -eq 0 ]; then
+        sync
+        umount -a
+        mount -o remount,ro /
+        kexec -e
+    fi
+    echo "kexec fail. ${err}"
+}
+
+parse_args() {
+    while getopts ':t:i:y' opt; do
+        case ${opt} in
+            t)
+                tmp_dir="${OPTARG}"
+                ;;
+            i)
+                mbd_initrd="${OPTARG}"
+                ;;
+            y)
+                yes_mode=1
+                ;;
+            \?|:)
+                return 1
+                ;;
+        esac        
+    done
+    shift $((OPTIND-1)); OPTIND=1
+    images_dir="$*"
+}
+
+parse_args "$@" || ! usage || exit_to_shell
+tmp_dir="${tmp_dir:-@tmp_dir@}"
+mbd_initrd="${mbd_initrd:-./mbd_initrd.gz}"
+images_dir="${images_dir:-./iso}"
+if [ -z "$(ls ${images_dir}/*.iso)" ]; then
+    msg="No ISO images found"
+    panic "${msg}"
+fi
+
 choose=''
-while [ -z "${choose}" ];do
-    show main_menu
-    case "${choose}" in
-        Live)
-	    if [ -n "$(ls '@mbd_dir@/mnt/@images_dir@/'*.iso)" ]; then
-		show images_menu
-	    else
-		show error_msg "No ISO images found"
-		choose=''
+while [ -z "${choose}" ]; do
+    show images_menu
+    if [ ${?} -eq 0 ] && [ -n "${choose}" ]; then
+        image="${images_dir}/${choose}.iso"
+        [ -x './@mbd_process_iso@' ] && cmd='./@mbd_process_iso@' || cmd='@mbd_process_iso@'
+        err=$("${cmd}" "${tmp_dir}" "${image}" 2>&1)
+        if [ ${?} -eq 0 ]; then
+            ask_confirmation 'The system will reboot (or crash). Continue?'
+            if [ ${?} -eq 0 ]; then
+                err=$(kexec_to "${choose}" 2>&1)
             fi
-            if [ 0 = ${?} ] && [ -n "${choose}" ]; then
-                image="@mbd_dir@/mnt/@images_dir@/${choose}.iso"
-                err=$(@mbd_process_iso@ '@mbd_dir@' "${image}" 2>&1)
-                if [ 0 = ${?} ]; then
-		    . @mbd_dir@/boot_default
-                    err=$(kexec_load '@mbd_dir@' "${kernel}" "${append}" "${initrd}" '@mbd_dir@/mnt/@isolinux_dir@/mbd_initrd.gz' "${choose}.iso" 2>&1)
-                    if [ 0  = ${?} ]; then
-                        kexec -e
-                        err="Failed to kexec. ${err}"
-                    fi
-                fi
-                if [ -n "${err}" ];then
-                    show error_msg "${err}"
-                fi
-                choose=''
-            else
-                choose=''
-            fi            
-            ;;
-        NetbootCD) 
-	    netbootcd
-	    choose=''
-            ;;
-        *)exit_to_shell;;
-    esac
+        fi
+        if [ -n "${err}" ]; then
+            show error_msg "${err}"
+        fi
+        choose=''
+    else
+       exit_to_shell
+    fi
 done
